var FollowConstants = {
  FETCH_FOLLOW_OBJECT: "FETCH_FOLLOW_OBJECT",
  TOGGLE_FOLLOW: "TOGGLE_FOLLOW",
  ALL_FOLLOWERS_AND_FOLLOWEES: "ALL_FOLLOWERS_AND_FOLLOWEES"
};

module.exports = FollowConstants;
