var UserAndPostConstants = {
  ADD_USER_OR_ALL_HIS_POSTS: "ADD_USER_OR_ALL_HIS_POSTS",
  ADD_NEW_USER_POST: "ADD_NEW_USER_POST",
  UPDATE_USER_POST: "UPDATE_USER_POST",
  DELETE_USER_POST: "DELETE_USER_POST",
  ALL_POSTS: "ALL_POSTS",
  BRING_DOWN_MATCHED_USERS: "BRING_DOWN_MATCHED_USERS"
};

module.exports = UserAndPostConstants;
